[project]
name = "stevewm"
version = "1.0.0"
description = "Profile README updater"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.5",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
